Repository warewulf/warewulf-node-images, pull requests merged in 2023-12, with the labels that each got.

#38 Fix cosign error during container build
  .github/workflows/container-publish.yml
Labels: bug

#39 Add --yes flag to cosign
  .github/workflows/container-publish.yml
Labels: bug

#40 Update container signing action from upstream example
  .github/workflows/container-publish.yml
Labels: enhancement

#41 Attempt cosign signing without a key
  .github/workflows/container-publish.yml
Labels: bug

#33 New Debian container
  .github/workflows/container-publish.yml
  CONTRIBUTORS.md
  debian/Containerfile
  debian/Containerfile-12.0
  debian/container_exit.sh
  debian/excludes
Labels: enhancement

#42 New example definition file, rockylinux-mofed
  README.md
  examples/README.md
  examples/rockylinux-9-mofed/Containerfile
  examples/rockylinux-9-mofed/README.md
Labels: documentation, enhancement
